export const GET_FIELD_ERRORS = 'GET_FIELD_ERRORS';
export const HAS_LOGIN_ERROR = 'HAS_LOGIN_ERROR';
export const SET_FIELD_ERROR = 'SET_FIELD_ERROR';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
