security:
    encoders:
        App\Entity\User\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Entity\User\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/user/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /user/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        persons:
            pattern:   ^/persons
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        refresh:
            pattern:  ^/user/token/refresh
            stateless: true
            anonymous: true

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/persons, roles: IS_AUTHENTICATED_FULLY }
